### ISSUE TITLE
Questions about PatchNceLoss

### ISSUE THREAD

**Issue by lintianwei-blog** [taesungp/contrastive-unpaired-translation#1]
Thanks for your released codes, it is a really interesting work.

During reading codes, I am confused about patchnceloss. In pseudo code, l_pos is calculated as 

`
l_pos = (f_k * f_q).sum(dim=1)[:, :, None] # BxSx1
`

However, in nce.py, it is calculated as:

`
l_pos = torch.bmm(feat_q.view(batchSize, 1, -1), feat_k.view(batchSize, -1, 1))
l_pos = l_pos.view(batchSize, 1) # B x 1
`
Is it wrong here?

**Comment by taesungp** [comment]
They are actually doing the same thing, because matrix multiplication is sum over product of f_k and f_q. But thank you for the catch. I will update the code to reduce confusion.

**Comment by lintianwei-blog** [comment]
I tried to print the output shape, and they are actually different.
The shape of l_pos in pseudo codes is BxSx1, and is Bx1 in nce.py.
In Pseudo codes:
sum(BxCxS, BxCxS, dim=1) -> BxS -> BxSx1
In nce.py:
torch.bmm( Bx1xCS, BxCSx1) -> Bx1

Is my understand of nce.py wrong?

**Comment by taesungp** [comment]
I see the source of confusion. `batchSize` of the nce.py code does not mean the batch size of the images.  It is the batch size of the patches, which is `BxS` in your comment. Such reshaping occurs inside netF. See https://github.com/taesungp/contrastive-unpaired-translation/blob/master/models/networks.py#L570. Therefore, in nce.py, assuming B is 1, we are doing

torch.bmm(BSx1xC, BSxCx1) -> BSx1

Let me know if this makes sense to you.

**Comment by lintianwei-blog** [comment]
I got it, Thanks!

**Comment by junyanz** [comment]
maybe we should add a detailed comment to that line. @taesungp
