### ISSUE TITLE
how to netG stylegan options?

### ISSUE THREAD

**Issue by kimtaehyeong** [taesungp/contrastive-unpaired-translation#10]
Thank you for your good research and I'm very interested in this research.
I have one question.

"""    
elif netG == 'stylegan2':
        net = StyleGAN2Generator(input_nc, output_nc, ngf, norm_layer=norm_layer, use_dropout=use_dropout, opt=opt)
"""

I want to use stylegan2 option in netG. But why specify generator architecture [resnet_9blocks | resnet_6blocks | unet_256 | unet_128]') Are there only options?

Thanks.

**Comment by junyanz** [comment]
You can use `stylegan2` or `smallstylegan2`.

**Comment by junyanz** [comment]
I added it to the `base_options.py` with the latest commit.
