### ISSUE TITLE
Understanding "real_B" in visualizations

### ISSUE THREAD

**Issue by tshead2** [taesungp/contrastive-unpaired-translation#103]
Thanks for this work!  I have a quick question about the "real_B" images in the results. If I understand the code correctly, these are simply randomly-chosen images from set "B" ... they have no particular relationship to the "real_A" or "fake_B" images, is that correct?

Many thanks,
Tim

**Comment by junyanz** [comment]
Yes, your understanding is correct. Real_B is just a random image from domain B. We use it to learn the discriminator.

**Comment by tshead2** [comment]
Excellent, thanks!
Tim
