### ISSUE TITLE
Creating the gif animations

### ISSUE THREAD

**Issue by rbunn80110** [taesungp/contrastive-unpaired-translation#113]
This is really great work and thank you for sharing the code!  

On the readme you have examples of image sequences gradually transforming from apples to oranges, summer to winter, etc.  Apologies if I am missing the obvious here, but I don't see any code that could generate the "in between" images so a gif could be created.  How would I generate those "in between" images?

**Comment by taesungp** [comment]
Sorry for the confusion. Those images were not really interpolated in the latent space. It's just a Powerpoint animation. It's not possible to generate those "in between" images.
