### ISSUE TITLE
FastCUT using custom dataset

### ISSUE THREAD

**Issue by oliver0922** [taesungp/contrastive-unpaired-translation#115]
Thanks for your reply.
By the way I want to change day time to night time using FastCUT.
After training the model using bdd1000k, I want to apply the model on KITTI datasets.
As you know, KITTI datasets are obtained only at day-time, so I dont have testB folder.
Do you have any suggestions? or Do I have to use SinCUT?

**Comment by taesungp** [comment]
The content of `testA` and `testB` won't affect training. They are only used as sample images to show the result after training is done. So you can put any image (same content as `testA`, for example).
