### ISSUE TITLE
Paper understanding

### ISSUE THREAD

**Issue by guitar9** [taesungp/contrastive-unpaired-translation#118]
I have read the CycleGAN Paper and understood it.  But in this paper I dont understand very much things. Can somebody maybe explain it in simple words what the idea behind cut is? Specially this thing with query and positive/ negativ sample.
Are patches randomly choosen in the image? 
Highly mutal informations means that the patches should have a high L1 Loss?

**Comment by taesungp** [comment]
You can watch [this video](https://youtu.be/16uAmmzBkGA?t=950) that explains what CUT is trying to do in the context of CycleGAN. Basically, when transforming a horse image into a zebra image, the body parts need to remain unchanged. The horse head should become a zebra head. We enforce this by making the horse head and zebra head similar, _compared_ to the other patches (patches of the horse body, or trees, for example).
