### ISSUE TITLE
Semantic preservation via mutual information

### ISSUE THREAD

**Issue by zhangmozhe** [taesungp/contrastive-unpaired-translation#12]
Thanks for this work. This work is definitely a milestone in image translation and I really love it.

I wonder why the semantics are disentangled by constraining the mutual information. Why the mutual information will not maintain the texture information? Thanks for your explanation.

**Comment by junyanz** [comment]
It depends on the datasets. The algorithm tends to preserve the shared information across two domains.  In several cases of our paper, domain A and B (e.g., horse2zebra) have dramatic texture differences but share similar semantic layouts. Therefore, the algorithm tends to preserve semantic information. If you train a model from (random texture, shape A) to (random texture, shape B), the algorithm might learn to retain the texture but change the shape.

**Comment by zhangmozhe** [comment]
Thanks for your explanation.
