### ISSUE TITLE
Viewing progress of image

### ISSUE THREAD

**Issue by ratheeshaditya** [taesungp/contrastive-unpaired-translation#120]
Hi is it possible to see the progress of one image over-time? Because every epoch a new image gets generated in visdom. But i would like to see how the quality of one image that is being generated over-time

Thanks :)

**Comment by taesungp** [comment]
Hello, there is no code to do that during training. But you can run the test code using a fixed set of sample images for each checkpoint.

**Comment by noveoko** [comment]
try looking in:
checkpoints/<your_model_name>/web/images/
That gives you images for both A and B classes by Epoch
