### ISSUE TITLE
Normalize to unit sphere?

### ISSUE THREAD

**Issue by jbeck9** [taesungp/contrastive-unpaired-translation#122]
The paper says "We normalize vectors onto a unit sphere to prevent the space from collapsing or expanding.". I can't seem to find the code dedicated to doing this, and I'm curious how it was done. Hoping someone could point me in the right direction.

Thanks

**Comment by taesungp** [comment]
It is done by performin [l2-normalization](https://github.com/taesungp/contrastive-unpaired-translation/blob/82dbc719df9cec7e92ef9e46f827830fea5d26dc/models/networks.py#L578) to adjust magnitude to 1.

**Comment by lifangda01** [comment]
The way it is implemented now normalizes along the spatial axis, not the channel axis. Think this is a bug.
