### ISSUE TITLE
[Solved] I'm able to train but can't test

### ISSUE THREAD

**Issue by Shadowless422** [taesungp/contrastive-unpaired-translation#125]
I trained a sincut model for 12 hours with default settings and my GPU memory usage (it's a RTX 3060 with 12GB of VRAM) was barely 4GBs. Now I tried to test it with the default settings and I'm unable to do it because i run out of memory (!?).

This is the error i get: 
`RuntimeError: CUDA out of memory. Tried to allocate 252.00 MiB (GPU 0; 12.00 GiB total capacity; 9.61 GiB already allocated; 0 bytes free; 9.87 GiB reserved in total by PyTorch) If reserved memory is >> allocated memory try setting max_split_size_mb to avoid fragmentation.`

I tried to find a solution but I couln't find one. I'm getting mad

**Comment by taesungp** [comment]
Sorry to hear that you are getting mad. I think it is because the input image resolution is very large. One option is to reduce the resolution of the input image until it fits on your GPU. Another thing is, your PyTorch application somehow did not use the full 12GB of memory, but only used 9.87GB. Do you know why this happened?

**Comment by Shadowless422** [comment]
Reducing the input image resolution worked flawlessly, thank you! 

About the fact that PyTorch was unable to use the full 12GB of memory I don’t know since I had nothing else open that would justify that. My best bet is that since I’m using Windows, the missing VRAM is being reserved for the system or some other Windows nonsense, but I’m not sure because if I train a CUT model with a batch size of 3 (and default settings), my VRAM usage reaches something like 11.2 GB, so it definitely exceeds the 9.87 GB.
Do you have any other ideas?

**Comment by taesungp** [comment]
If the graphic card was also used to run the monitor display, it will reserve some memory for that. Glad to hear the issue is somewhat resolved!
