### ISSUE TITLE
AttributeError: 'Namespace' object has no attribute 'G_n_downsampling' , options netG stylegan2

### ISSUE THREAD

**Issue by chokyungjin** [taesungp/contrastive-unpaired-translation#13]
Thank you for your good research and I'm very interested in this research.
I have one question.

your last commit add base options like this

'''
parser.add_argument('--netD', type=str, default='basic', choices=['basic', 'n_layers', 'pixel', 'patch', 'tilestylegan2', 'stylegan2'], help='specify discriminator architecture. The basic model is a 70x70 PatchGAN. n_layers allows you to specify the layers in the discriminator')
parser.add_argument('--netG', type=str, default='resnet_9blocks', choices=['resnet_9blocks', 'resnet_6blocks', 'unet_256', 'unet_128', 'stylegan2', 'smallstylegan2', 'resnet_cat'], help='specify generator architecture')

'''
But It still haven't solved that netG , net D param. 
Can you tell me how to do it?
Thanks.

**Comment by taesungp** [comment]
Hello, do you mean you are not sure which `--netG` and `--netD` to use? Our default setting `--netG resnet_9blocks --netD basic` should work. The other architectures, such as stylegan2 architecture, will be used in our next release when single image translation is trained.

**Comment by majdzr** [comment]
FYI, the Unet128 and Unet256 also fail as netG.

**Comment by taesungp** [comment]
We added the support for the stylegan2-based networks, designed for the single-image translation. UNet is designed to be used for the CycleGAN baseline, and we don't have support for UNet-based models for CUT.
