### ISSUE TITLE
Some generated images are left-right flipped

### ISSUE THREAD

**Issue by russelldj** [taesungp/contrastive-unpaired-translation#130]
Hi all,

Great work. Perhaps this is a one-off error but I found it interesting. While training with `FastCUT` and an input resolution of `512x512` I found that some of my generated images are left-right flipped. Surprisingly, the structure seems like it would match if the image were flipped back. Here are some examples
![Untitled](https://user-images.githubusercontent.com/29384527/161567590-52371dab-afc4-4262-bd07-ff4b2d0a0a22.png)
![Untitled (1)](https://user-images.githubusercontent.com/29384527/161567652-e2b5e564-1d49-4cb5-8ca5-6a46f7094aa0.png)
![Untitled (2)](https://user-images.githubusercontent.com/29384527/161567661-2e5ab37b-c6f3-48ef-ae8b-e789267eb3a7.png)

**Comment by taesungp** [comment]
Strange! Could you disable flipping when you run this and see if it still happens? `--no_flip` is the command line option.

**Comment by Hirnmoder** [comment]
Well, I don't think it's that strange. It is just how `FastCUT` is implemented.
- [models/cut_model.py Line 48](https://github.com/taesungp/contrastive-unpaired-translation/blob/master/models/cut_model.py#L48): Option `flip_equivariance` is enabled for `FastCUT` by default
- [models/cut_model.py Lines 149 to 154](https://github.com/taesungp/contrastive-unpaired-translation/blob/master/models/cut_model.py#L149-L154): The input image is flipped (50% chance) and consequently the output image `self.fake` is flipped, too
- `self.fake` does not get flipped back &rarr; hence, we see the horizontally flipped image in visom


Now regarding the other parts of the question:
- The third image is `real_B`, so there is no such thing as a "structure"
- Visdom shows the properties `real_A`, `fake_B` and `real_B`. But `real_A` contains the *non-flipped* original image, `fake_B` however contains the *flipped* fake image

**Comment by russelldj** [comment]
Thanks for figuring this out.
