### ISSUE TITLE
More Pretrained Models?

### ISSUE THREAD

**Issue by Hirnmoder** [taesungp/contrastive-unpaired-translation#133]
In [Readme Line 192](https://github.com/taesungp/contrastive-unpaired-translation/blob/master/README.md?plain=1#L192) I found a link to download pretrained models for CUT. (http://efrosgans.eecs.berkeley.edu/CUT/pretrained_models.tar)

Unfortunately, it seems that this link is broken (404) and therefore I cannot download the models (training the models myself takes a lot more time of course). Is there any other download link available or may you consider checking them into the repository?

**Comment by Hirnmoder** [comment]
It seems that accessing the above mentioned URL with a webbrowser that enforces HTTPS results in this 404-Not-Found-Issue. The file can be downloaded via any other browser or (if you are on Windows) with this PowerShell command:

````
Invoke-WebRequest -Uri http://efrosgans.eecs.berkeley.edu/CUT/pretrained_models.tar -OutFile pretrained_models.tar
````

I'll update the issue title as the file contains the following pretrained models:
- cat2dog CUT
- cat2dog FastCUT
- cityscapes CUT
- cityscapes FastCUT
- horse2zebra CUT
- horse2zebra FastCUT

Is there any chance to get pretrained models for other datasets (e.g. iphone2dlsr, grumpifycat, ...)?

**Comment by taesungp** [comment]
Hi Hirnmoder, I unfortunately do not have other models. Sorry about that!

Yes, the HTTP/HTTPS thing for the provided link is not ideal, but I think `wget` command doesn't have this problem?

**Comment by Hirnmoder** [comment]
Hi taesungp, thank you for clarifying the pretrained model situation.

Yes, indeed, the `wget` command or `Invoke-WebRequest` (if you are on Windows) does not suffer from the HTTP/S issue. Therefore I was able to download the aforementioned models. Thank you for providing the models!

I'll close this issue as the main question (more pretrained models) has been answered.
