### ISSUE TITLE
Doubt in PatchNCE loss 

### ISSUE THREAD

**Issue by tejank10** [taesungp/contrastive-unpaired-translation#14]
Hi @taesungp , awesome work! Thank you for making the research code open source.

I am having a small question [here](
https://github.com/taesungp/contrastive-unpaired-translation/blob/24e03ceeb8c0bc169ee9a06bed0689323a06c5d7/models/patchnce.py#L16) in the definition of PatchNCE loss. Why is it required to detach the features here and what issue would arise if it is not detached? Thanks.

**Comment by taesungp** [comment]
Hi @tejank10 

Great point! We detached the negatives to match the setting of MoCo for comparison. I don't remember if that has a noticeable impact on the result. Perhaps you can try removing it and tell us what happens! ;-)
