### ISSUE TITLE
Possible failure cases

### ISSUE THREAD

**Issue by hedjm** [taesungp/contrastive-unpaired-translation#15]
Thanks for this great work, I have a question regarding some possible failure cases which may be related to hyperparameters choices. What if the image contains patches with **high similarity**, in other words, let's consider an image of a synthetic hand, we want to translate it to a real hand, different patches in the source image are very similar, how do you choose the negative patches in this case? The same thing applies for the horse/zebra images, if we take the grass as a positive patch, how do you eliminate the other grass patches? In other words, you can find false negatives in the internal image.

**Comment by taesungp** [comment]
Even in those cases, we believe that the best way to satisfy the contrastive loss is to maintain as much information of the source patch as possible. Different patches of grass will still be slightly different. For example, the texture pattern will be different, or there may be a distinct object within the receptive field. The best strategy for minimizing the contrastive loss would be preserving these distinctive features before and after translation, and use them for embedding the output close to the source. In a sense, our contrastive loss encourages the feature encoder to focus on _whatever that makes a particular patch different from other patches_. Hope this makes sense to you!

**Comment by hedjm** [comment]
@taesungp Thanks for your reply.
