### ISSUE TITLE
the necessity of data_dependent_initialize

### ISSUE THREAD

**Issue by Turlan** [taesungp/contrastive-unpaired-translation#21]
Hi, great work! Thanks for releasing codes. I am confused about the data_dependent_initialize step. Could you explain why we need this extra step before the real training starts？

https://github.com/taesungp/contrastive-unpaired-translation/blob/24e03ceeb8c0bc169ee9a06bed0689323a06c5d7/train.py#L43

**Comment by QtacierP** [comment]
If you do not set this function, you will get some troubles when you use multiple GPUs. The MLP flag will be initialized and fixed when you use the nn.DataParallel() to replace the naive model (nn.Module). Therefore, we need to initialize the MLP before we parallelize the model

**Comment by ibro45** [comment]
@QtacierP does that imply that there's no other purpose to it except that it's patching the issue with `nn.DataParallel()` and that if nn.DataParallel() is not used, we can safely remove it?
