### ISSUE TITLE
Question about image pool 

### ISSUE THREAD

**Issue by QtacierP** [taesungp/contrastive-unpaired-translation#22]
Thanks for presenting such awesome and solid work! 
I am confused about the setting of the image pool in CutGAN. I think that an image pool can make the discriminator more robust with an unpaired input training data, but I noticed that you have abandoned it in the CutGAN. Could you please tell me the reason?

**Comment by taesungp** [comment]
We did not observe a big difference with image pool. For simplicity, we did not use image pool.

**Comment by QtacierP** [comment]
Thanks for your answer. I got it!
