### ISSUE TITLE
Is `gpu_ids -1` flag ignored?

### ISSUE THREAD

**Issue by inneon** [taesungp/contrastive-unpaired-translation#24]
**System**
Ububtu 20.04
No CUDA GPU

**Steps** 
`bash ./datasets/download_cut_dataset.sh grumpifycat`
`python train.py --dataroot ./datasets/grumpifycat --name grumpycat_CUT --CUT_mode CUT --gpu_ids -1`

**Results**
```
...
gpu_ids: -1 [default: 0]
...
Traceback (most recent call last):
  File "train.py", line 39
...
Found no NVIDIA driver on your system...
```

**Expected**
Should be consistent with readme stating CPU processing is possible.

**Comment by taesungp** [comment]
Thank you for pointing it out. We added support for CPU training in the latest commit.
