### ISSUE TITLE
the patch nums for different input resolution

### ISSUE THREAD

**Issue by Turlan** [taesungp/contrastive-unpaired-translation#26]
The default setting of  num_patches is 256 for input images with  resolution of 256x256.
https://github.com/taesungp/contrastive-unpaired-translation/blob/24e03ceeb8c0bc169ee9a06bed0689323a06c5d7/models/cut_model.py#L32
I am wondering this hyperparameter's effects, have you ever tried other numbers?
Besides, what if the input image resolution is changed (e.g. 400x400), should we change the num_patches for better results ?

**Comment by taesungp** [comment]
We did try smaller numbers in the paper (see **Negs** of Fig 4 of the paper), and using larger number of patches does help stability. We found that the default value of 256 can be used quite universally. For our GTA2Cityscapes results, the training resolution of cropped images was 512x512, but we used the default value.
