### ISSUE TITLE
An error in the last line in train.py

### ISSUE THREAD

**Issue by laulampaul** [taesungp/contrastive-unpaired-translation#27]
I face an error.
AttributeError: 'CUTModel' object has no attribute 'update_11learning_rate'
where is the update_11learning_rate function ?

**Comment by taesungp** [comment]
I think it is `update_learning_rate` called at the last line of train.py, but somehow it was mistyped as `update_11learning_rate`. I couldn't find such word in the current github repo. Could that be an accidental typo on your machine?

**Comment by laulampaul** [comment]
Thank you!
