### ISSUE TITLE
How to Add Cycle Loss?

### ISSUE THREAD

**Issue by chokyungjin** [taesungp/contrastive-unpaired-translation#28]
Hi. I want to add cycle loss in CUT.
I know this model doesn't need cycle loss. But I want to experiment with recon image!

Thanks Again.

**Comment by junyanz** [comment]
We have a cyclegan model included in this repo. Here is the [loss](https://github.com/taesungp/contrastive-unpaired-translation/blob/master/models/cycle_gan_model.py#L182). But you also need to add 1 more generator and discriminator and their optimizers.

**Comment by taesungp** [comment]
Yes, for experimenting with CycleGAN, you can take a look at `models/cycle_gan_model.py`, and combine its code with `cut_model.py`.
