### ISSUE TITLE
Continue Learning

### ISSUE THREAD

**Issue by martinUB** [taesungp/contrastive-unpaired-translation#29]
I was wondering, if i could give the train command an flag for an already trained network, after i had to cancel training? Haven't found this function and neither an indicator in the code in train.py

Cheers and thanks for the awesome project!
Martin

**Comment by taesungp** [comment]
Hi, that is possible by using a combination of flags. 

`--continue_train --epoch_count X --epoch Y`

`--continue_train` will try to load an existing checkpoint. In particular, it looks for checkpoint at `[checkpoint_dir]/[name]/[epoch]_net_*.pth`, where each of `checkpoint_dir, name, epoch` is retrieved from the options. 

In short, just add `--continue_train --epoch_count 51 --epoch 50` to your training script to load `50_net_*.pth` and resume training from epoch 51.
