### ISSUE TITLE
NCE layers selection

### ISSUE THREAD

**Issue by JunlinHan** [taesungp/contrastive-unpaired-translation#30]
Hi all,
Thanks for your wonderful work and code.
I'm wondering about the selection of NCE layers. Why you select '0,4,8,12,16' as default layers? For better feature extractions or it just works fine? Is this default setting designed for RESNET-9?
And, If we change the generator, we have to reconsider the selection of NCE layers. Is that correct?

Thanks in advance for any replies!

**Comment by taesungp** [comment]
The default setting is designed for ResNet9. We counted the layers of the ResNet9 architecture to include the pixel layer, output of downsampling conv layers, and output of resnet layers. 
Therefore, if the generator is changed, the NCE layers needs to be reconsidered.
