### ISSUE TITLE
Something Wrong input image!

### ISSUE THREAD

**Issue by chokyungjin** [taesungp/contrastive-unpaired-translation#31]
Hi! I'm so glad to meet your Paper and Code! But I have a question.
I trained using image of size 1024 x 1024 in a pretreatment as a resize and crop.
But html is spitting out some weird results. Input image is blank? My dataset doesn't have any problem.
How Can I Solve this?

![image](https://user-images.githubusercontent.com/46750574/93172071-256ed700-f765-11ea-9942-795c4fece360.png)

Thanks again!

**Comment by taesungp** [comment]
could you specify the options you used? Do you see something reasonable on visdom display during training?

**Comment by chokyungjin** [comment]
running script is 
python train.py --dataroot /workspace/data/celeba_hq/train --name grumpycat_CUT --CUT_mode CUT --checkpoints_dir b1_checkpoints --verbose --load_size 512 --crop_size 512 --batch_size 1

And I only applied resize transform, not using any preprocess in your code.

Thanks!

**Comment by taesungp** [comment]
I think there's something wrong about scaling of input / output values here. White real_A means all pixel values are saturated at 1.0, and grey fake_B means all values are 0. Do you see something reasonable on visdom display during training?

**Comment by chokyungjin** [comment]
utils/visualizer.py 137 lines.
white_image = np.ones_like(image_numpy.transpose([2, 0, 1])) * 255
Is it Ok to erase * 255 ?

**Comment by chokyungjin** [comment]
Oh, My mistake.
One of my dataset is 16-bit image , so result image is weird.
Thanks
