### ISSUE TITLE
Question about the data preprocessing

### ISSUE THREAD

**Issue by laulampaul** [taesungp/contrastive-unpaired-translation#35]
I notice that in the training stage, you resize and crop the image into 256. But when I dont resize the image, it seems that the results get worse. Maybe the NCE loss cannot distinguish the similar patches. 
Do you try other crop size or dont resize the original image in the experiment ? Thank you !

**Comment by taesungp** [comment]
We did experiment with `--preprocess scale_with_and_crop --load_size 1024 --crop_size 512` for GTA2Cityscapes dataset, and that worked for us. As for the NCE loss, we are only computing the NCE loss between the preprocessed input x and the output G(x) as the positive pair, so the choice of preprocessing should not affect training. However, it is possible that some resolution is better than another. For example, if the image is too high resolution, there may not be enough signal in each local region to distinguish that location from other patches.
