### ISSUE TITLE
SinCUT Single Image Unpaired Training

### ISSUE THREAD

**Issue by ak9250** [taesungp/contrastive-unpaired-translation#4]
great work, waiting for single image upaired training steps

**Comment by junyanz** [comment]
@taesungp

**Comment by cpatrickalves** [comment]
Awesome work! 
I am really excited to try Single CUT also. 
@junyanz  and @taesungp , any idea when it will be available?

**Comment by taesungp** [comment]
In a few weeks! Thank you for the interest.
