### ISSUE TITLE
Confusing typo in the paper

### ISSUE THREAD

**Issue by TropComplique** [taesungp/contrastive-unpaired-translation#5]
Hi!
I like your paper a lot.

There is a typo in the formula 3 (definition of PatchNCE loss):
the query patch is not in the translated image (y hat) but in the original (x).
It contradicts the figure 2 and the implementation.
So you need to swap `z^s_l` and `hat z^s_l`.

The typo is confusing because maybe this definition of the loss will work also.

**Comment by junyanz** [comment]
Yes, you are correct. We will fix it in arxiv v2.
