### ISSUE TITLE
Applying to 1024 x 1024 resolution

### ISSUE THREAD

**Issue by bindita** [taesungp/contrastive-unpaired-translation#6]
I need to apply this code to 1024 x 1024 images. Should I change the architecture of resnet_9blocks and/or the discriminator architecture to get better fidelity in the results or will the basic settings work fine?
I couldn't fit the default network in my GPU, so I made the following changes. Do they make sense?

- increased n_downsampling in ResnetGenerator from 2 to 4
- reduced ngf (#filters for G) from 64 to 32 but kept 9 resblocks
- increased n_layers_D from 3 to 4

**Comment by junyanz** [comment]
Feel free to try your new G and D. Alternatively, what we found effective in practice is to train our model on cropped patches (e.g., 512x512 cropped images from your 1024x1024). You can do it with `--preprocess crop --load_size 1024 --crop_size 512`.   You can test the model with `--preprocess none`.
