### ISSUE TITLE
Typo in Citation

### ISSUE THREAD

**Issue by ced-mos** [taesungp/contrastive-unpaired-translation#7]
Hello,

First, thanks for your great work :).
To only small error I have seen is in a typo in your README.md file under the citation for your original cycleGAN paper.

You have one letter 's' at the end too much in your citation name. It should be "Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks" and not "Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks**s**"

`@inproceedings{CycleGAN2017,
  title={Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networkss},`

**Comment by junyanz** [comment]
Thanks a lot. I just fixed it.
