### ISSUE TITLE
Is it not need Large Batch size?

### ISSUE THREAD

**Issue by chokyungjin** [taesungp/contrastive-unpaired-translation#8]
Hi! I'm so glad to meet your Paper and Code! But I have a question.
I learned that Contrasitive Learning needs a large batch size.
But when I 'm training your code my custom data, it is running a 24G GPU and Batch size 8, 
and Model makes  good results!!
How is this possible?

Thanks again!

**Comment by taesungp** [comment]
Yes, thank you @hedjm for pointing it out! I just want to add that our contrastive loss is enforced on 256 patches for each of the 5 layers per image. So in fact, we do use a modest number ( > 1000) of negatives per each image. But they all come from the same image, so the batch size of our data loader is 1.
