### ISSUE TITLE
What image sizes are supported for training and inference?

### ISSUE THREAD

**Issue by turian** [taesungp/contrastive-unpaired-translation#84]
Could you please provide a little guidance in the README about what image sizes are supported for training and inference?

e.g. height and width must be multiples of 256? Something more constrained? etc.

Related to #69

**Comment by George-Ogden** [comment]
They can be any size and then they will be resized to `--load_size` and then cropped to `--crop_size`

**Comment by taesungp** [comment]
I added some description about image preprocessing in [README](https://github.com/taesungp/contrastive-unpaired-translation#preprocessing-of-input-images).
