### ISSUE TITLE
Question about some specific use case

### ISSUE THREAD

**Issue by cpatrickalves** [taesungp/contrastive-unpaired-translation#9]
@taesungp and @junyanz 

Thanks for sharing this great project. 

I don't have too much experience with this kind of project (just basic deep learning models).
But I am trying to use your project to accomplish a task and I am wondering if you could answer a few questions.

Basically I am trying to add skin issues on faces. So I get a picture of someone and want to add acne or pimples on it. 
Now, I am training a model using the celebaHQ dataset (3k images on TrainA) and 17 images (TrainB) with people with severe acne to see the results (I have just a few examples). 
The model is still training, but here are some outputs:

![image](https://user-images.githubusercontent.com/22003608/90673876-b5853380-e22e-11ea-8f5d-7f09e1a79ea2.png)

![image](https://user-images.githubusercontent.com/22003608/90673935-cafa5d80-e22e-11ea-9332-96622045f06e.png)

I am using the CUT model with default settings.

1) Are there some parameters that I should take a look for tunning the model?
2) First, I've tested with just 15 pictures on trainA, but the results were terrible, so I know that the amount of data on TrainA it's important. My question is: how much data should I put on TrainB? I am using only 17, I not sure if I used 50 or 100 would make a difference.

regards,
Patrick

**Comment by junyanz** [comment]
You probably want to train the model longer (like 400 epoches). For a better result, you need to collect more images (hundreds or thousands per domain). Also, make sure that you align the face to a canonical pose. It seems that faces in B are not aligned.

**Comment by cpatrickalves** [comment]
Thanks for the answer @junyanz 
I am also excited to try the  Single-Image Translation. 
Do you think I can get a better results with SinCUT for this specific use case?

**Comment by taesungp** [comment]
SinCUT does not gain any general knowledge extracted from the dataset, so for SinCUT, it's very important that the target reference image has similar structure as the source. Choosing a suitable target reference image might be a nontrivial problem.
